/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rw.rab.view;

/**
 *
 * @author nsumba
 */
public class FundInvoice extends javax.swing.JFrame {

    private rw.rab.model.User loggedInUser;
    private rw.rab.service.InvoiceService invoiceService;
    private rw.rab.service.InvestorService investorService;
    private rw.rab.service.FundingService fundingService;
    private int selectedInvoiceId = -1;

    public FundInvoice(rw.rab.model.User user) {
        initComponents();
        this.loggedInUser = user;
        setLocationRelativeTo(null);
        connectToServer();
        addPlaceholder(amountField, "Enter amount");
        addPlaceholder(selectedInvoiceField, "Auto Filled on Selected Invoice");
        loadVerifiedInvoices();
        loadMyFundings();
        setupTableClickListener();
        confirmFundingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmFundingBtnActionPerformed(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dispose();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        availableInvoiceTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        amountField = new javax.swing.JTextField();
        confirmFundingBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        selectedInvoiceField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        myHistroryTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(24, 95, 165));

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel1.setText("Fund Invoices");

        jButton1.setFont(new java.awt.Font("DejaVu Sans", 0, 15)); // NOI18N
        jButton1.setText("Back to Dashboard");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        availableInvoiceTable.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        availableInvoiceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Invoice#", "SME", "Amount", "Issue Date", "Due Date", "Status"
            }
        ));
        jScrollPane1.setViewportView(availableInvoiceTable);

        jLabel2.setText("Available Verified Invoices ");

        jLabel4.setFont(new java.awt.Font("Ubuntu Sans", 0, 12)); // NOI18N
        jLabel4.setText("Selected Invoice#");

        amountField.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        amountField.setForeground(new java.awt.Color(100, 100, 100));
        amountField.setText("Enter amount");
        amountField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountFieldActionPerformed(evt);
            }
        });

        confirmFundingBtn.setBackground(new java.awt.Color(24, 95, 165));
        confirmFundingBtn.setText("Confirmed Funding");

        jLabel5.setFont(new java.awt.Font("Ubuntu Sans", 0, 12)); // NOI18N
        jLabel5.setText("Amount to Fund(RWF)");

        selectedInvoiceField.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        selectedInvoiceField.setForeground(new java.awt.Color(100, 100, 100));
        selectedInvoiceField.setText("Auto Filled on Selected Invoice");
        selectedInvoiceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectedInvoiceFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(confirmFundingBtn)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(selectedInvoiceField, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(amountField, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectedInvoiceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmFundingBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setText("Fund Selected Invoice");

        jLabel6.setText("My Funding History");

        myHistroryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Invoice#", "Amount", "Date"
            }
        ));
        jScrollPane2.setViewportView(myHistroryTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void amountFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountFieldActionPerformed

    private void selectedInvoiceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectedInvoiceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectedInvoiceFieldActionPerformed

    private void connectToServer() {
        try {
            java.rmi.registry.Registry registry = java.rmi.registry.LocateRegistry.getRegistry("127.0.0.1", 3000);
            invoiceService = (rw.rab.service.InvoiceService) registry.lookup("invoice");
            investorService = (rw.rab.service.InvestorService) registry.lookup("investor");
            fundingService = (rw.rab.service.FundingService) registry.lookup("funding");
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Cannot connect to server: " + e.getMessage(),
                "Connection Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    private void loadVerifiedInvoices() {
        try {
            java.util.List<rw.rab.model.Invoice> allInvoices = invoiceService.getAllInvoices();
            javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(
                new String[]{"ID", "Invoice #", "SME", "Amount", "Due Date", "Status"}, 0
            );
            for (int i = 0; i < allInvoices.size(); i++) {
                rw.rab.model.Invoice inv = allInvoices.get(i);
                if (inv.getStatus().equals("VERIFIED")) {
                    model.addRow(new Object[]{
                        inv.getInvoiceId(),
                        inv.getInvoiceNumber(),
                        inv.getSme() != null ? inv.getSme().getBusinessName() : "",
                        inv.getAmount(),
                        inv.getDueDate(),
                        inv.getStatus()
                    });
                }
            }
            availableInvoiceTable.setModel(model);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Error loading invoices: " + e.getMessage(),
                "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    private void loadMyFundings() {
        try {
            rw.rab.model.Investor investor = getOrCreateInvestorProfile();
            if (investor == null) return;

            java.util.List<rw.rab.model.Funding> fundings = fundingService.getFundingsByInvestorId(investor);
            javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(
                new String[]{"ID", "Invoice #", "Amount Funded", "Date"}, 0
            );
            for (int i = 0; i < fundings.size(); i++) {
                rw.rab.model.Funding f = fundings.get(i);
                model.addRow(new Object[]{
                    f.getFundingId(),
                    f.getInvoice() != null ? f.getInvoice().getInvoiceNumber() : "",
                    f.getFundedAmount(),
                    f.getFundedDate()
                });
            }
            myHistroryTable.setModel(model);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Error loading fundings: " + e.getMessage(),
                "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    private void setupTableClickListener() {
        availableInvoiceTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int row = availableInvoiceTable.getSelectedRow();
                if (row != -1) {
                    selectedInvoiceId = (int) availableInvoiceTable.getValueAt(row, 0);
                    selectedInvoiceField.setText(
                        availableInvoiceTable.getValueAt(row, 1).toString()
                    );
                }
            }
        });
    }

    private void confirmFundingBtnActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            if (selectedInvoiceId == -1 || selectedInvoiceField.getText().trim().isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Please select an invoice from the table first",
                    "Validation Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (isPlaceholder(amountField, "Enter amount") || amountField.getText().trim().isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Please enter the amount to fund",
                    "Validation Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            double amount;
            try {
                amount = Double.parseDouble(amountField.getText().trim());
            } catch (NumberFormatException ex) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Amount must be a valid number",
                    "Validation Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (amount <= 0) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Funding amount must be greater than zero",
                    "Business Rule Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            rw.rab.model.Investor investor = getOrCreateInvestorProfile();
            if (investor == null) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "No investor profile found for this account. Contact admin.",
                    "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (amount > investor.getAvailableBalance()) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Funding amount exceeds your available balance of RWF " + investor.getAvailableBalance(),
                    "Business Rule Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            rw.rab.model.Invoice invoice = new rw.rab.model.Invoice();
            invoice.setInvoiceId(selectedInvoiceId);
            rw.rab.model.Invoice fullInvoice = invoiceService.getInvoiceById(invoice);

            if (!fullInvoice.getStatus().equals("VERIFIED")) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "This invoice is no longer available for funding. Status: " + fullInvoice.getStatus(),
                    "Business Rule Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            rw.rab.model.Funding funding = new rw.rab.model.Funding();
            funding.setFundedAmount(amount);
            funding.setFundedDate(new java.util.Date());
            funding.setInvoice(fullInvoice);
            funding.setInvestor(investor);

            fundingService.createFunding(funding);

            fullInvoice.setStatus("FUNDED");
            invoiceService.updateInvoice(fullInvoice);

            investor.setAvailableBalance(investor.getAvailableBalance() - amount);
            investorService.updateInvestor(investor);

            javax.swing.JOptionPane.showMessageDialog(this,
                "Funding confirmed successfully! RWF " + amount + " invested.",
                "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);

            selectedInvoiceField.setText("Auto Filled on Selected Invoice");
            selectedInvoiceField.setForeground(new java.awt.Color(100, 100, 100));
            amountField.setText("Enter amount");
            amountField.setForeground(new java.awt.Color(100, 100, 100));
            selectedInvoiceId = -1;

            loadVerifiedInvoices();
            loadMyFundings();

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Error: " + e.getMessage(),
                "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    private rw.rab.model.Investor getOrCreateInvestorProfile() {
        try {
            rw.rab.model.Investor investor = investorService.getInvestorByUserId(loggedInUser);
            if (investor != null) {
                return investor;
            }

            rw.rab.model.Investor newInvestor = new rw.rab.model.Investor();
            newInvestor.setFullName(loggedInUser.getUsername());
            newInvestor.setPhone("");
            newInvestor.setAvailableBalance(0);
            newInvestor.setUser(loggedInUser);
            investorService.createInvestor(newInvestor);

            return investorService.getInvestorByUserId(loggedInUser);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Error preparing investor profile: " + e.getMessage(),
                "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return null;
        }
    }

    private void addPlaceholder(final javax.swing.JTextField field, final String placeholder) {
        field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (field.getText().equals(placeholder)) {
                    field.setText("");
                    field.setForeground(new java.awt.Color(0, 0, 0));
                }
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                if (field.getText().trim().isEmpty()) {
                    field.setText(placeholder);
                    field.setForeground(new java.awt.Color(100, 100, 100));
                }
            }
        });
    }

    private boolean isPlaceholder(javax.swing.JTextField field, String placeholder) {
        return field.getText().trim().equals(placeholder);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FundInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FundInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FundInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FundInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FundInvoice(new rw.rab.model.User()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountField;
    private javax.swing.JTable availableInvoiceTable;
    private javax.swing.JButton confirmFundingBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable myHistroryTable;
    private javax.swing.JTextField selectedInvoiceField;
    // End of variables declaration//GEN-END:variables
}
