/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rw.rab.view;

import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import rw.rab.model.Invoice;
import rw.rab.service.InvoiceService;

/**
 *
 * @author nsumba
 */
public class InvoiceManagement extends javax.swing.JFrame {

    /**
     * Creates new form UserManagement
     */
   private InvoiceService invoiceService;

    public InvoiceManagement() {
        initComponents();
        setLocationRelativeTo(null);
        connectToServer();
        loadAllInvoices();
        statusCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusComboActionPerformed(evt);
            }
        });
    }

    private void connectToServer() {
        try {
            Registry registry = LocateRegistry.getRegistry("127.0.0.1", 3000);
            invoiceService = (InvoiceService) registry.lookup("invoice");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Cannot connect to server: " + e.getMessage(),
                "Connection Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    private void loadAllInvoices() {
    try {
        List<Invoice> invoices = invoiceService.getAllInvoices();
        DefaultTableModel model = new DefaultTableModel(
            new String[]{"ID", "Invoice #", "SME", "Amount", 
                         "Issue Date", "Due Date", "Status"}, 0
        );
        for (int i = 0; i < invoices.size(); i++) {
            Invoice inv = invoices.get(i);
            model.addRow(new Object[]{
                inv.getInvoiceId(),
                inv.getInvoiceNumber(),
                inv.getSme() != null ? inv.getSme().getBusinessName() : "",
                inv.getAmount(),
                inv.getIssueDate(),
                inv.getDueDate(),
                inv.getStatus()
            });
        }
        invoicesTable.setModel(model);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
            "Error loading invoices: " + e.getMessage(),
            "Error", JOptionPane.ERROR_MESSAGE);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        verifyBtn = new javax.swing.JButton();
        markAsFundedBtn = new javax.swing.JButton();
        markAsRepaidBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JToggleButton();
        searchInvoiceTxt = new javax.swing.JTextField();
        searchInvoiceBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        invoicesTable = new javax.swing.JTable();
        statusCombo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(24, 95, 165));

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel1.setText("Manage Invoices");

        jButton1.setFont(new java.awt.Font("DejaVu Sans", 0, 15)); // NOI18N
        jButton1.setText("Back to Dashboard");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        verifyBtn.setBackground(new java.awt.Color(29, 95, 165));
        verifyBtn.setText("Verify Selected");
        verifyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifyBtnActionPerformed(evt);
            }
        });

        markAsFundedBtn.setText("Mark As Funded");
        markAsFundedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markAsFundedBtnActionPerformed(evt);
            }
        });

        markAsRepaidBtn.setText("Mark As Repaid");
        markAsRepaidBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markAsRepaidBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        searchInvoiceTxt.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        searchInvoiceTxt.setForeground(new java.awt.Color(100, 100, 100));
        searchInvoiceTxt.setText("Search By Invoice Number");
        searchInvoiceTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchInvoiceTxtActionPerformed(evt);
            }
        });

        searchInvoiceBtn.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        searchInvoiceBtn.setText("Search");
        searchInvoiceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchInvoiceBtnActionPerformed(evt);
            }
        });

        invoicesTable.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        invoicesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Invoice", "SME", "Amount", "Issue Date", "Due Date", "Status"
            }
        ));
        jScrollPane1.setViewportView(invoicesTable);

        statusCombo.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        statusCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Status", "Pending", "Verified", "Funded", "Rejected" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(verifyBtn)
                                .addGap(47, 47, 47)
                                .addComponent(markAsFundedBtn)
                                .addGap(46, 46, 46)
                                .addComponent(markAsRepaidBtn)
                                .addGap(36, 36, 36)
                                .addComponent(deleteBtn))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(291, 291, 291)
                                .addComponent(searchInvoiceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(searchInvoiceBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(statusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchInvoiceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchInvoiceBtn)
                    .addComponent(statusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(verifyBtn)
                    .addComponent(markAsFundedBtn)
                    .addComponent(markAsRepaidBtn)
                    .addComponent(deleteBtn))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 123, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchInvoiceTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchInvoiceTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchInvoiceTxtActionPerformed

    private void verifyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifyBtnActionPerformed
        try {
        int selectedRow = invoicesTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this,
                "Please select an invoice to verify",
                "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String currentStatus = invoicesTable.getValueAt(
            selectedRow, 6).toString();

        // Business rule — only SUBMITTED invoices can be verified
        if (!currentStatus.equals("SUBMITTED")) {
            JOptionPane.showMessageDialog(this,
                "Only SUBMITTED invoices can be verified. " +
                "Current status: " + currentStatus,
                "Business Rule Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int invoiceId = (int) invoicesTable.getValueAt(selectedRow, 0);
        Invoice invoice = new Invoice();
        invoice.setInvoiceId(invoiceId);
        invoice.setStatus("VERIFIED");

        String result = invoiceService.updateInvoice(invoice);
        JOptionPane.showMessageDialog(this,
            "Invoice verified successfully",
            "Success", JOptionPane.INFORMATION_MESSAGE);
        loadAllInvoices();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
            "Error: " + e.getMessage(),
            "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_verifyBtnActionPerformed

    private void markAsFundedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markAsFundedBtnActionPerformed
        try {
        int selectedRow = invoicesTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this,
                "Please select an invoice",
                "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String currentStatus = invoicesTable.getValueAt(
            selectedRow, 6).toString();

        // Business rule — only VERIFIED invoices can be funded
        if (!currentStatus.equals("VERIFIED")) {
            JOptionPane.showMessageDialog(this,
                "Only VERIFIED invoices can be marked as funded",
                "Business Rule Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int invoiceId = (int) invoicesTable.getValueAt(selectedRow, 0);
        Invoice invoice = new Invoice();
        invoice.setInvoiceId(invoiceId);
        invoice.setStatus("FUNDED");

        invoiceService.updateInvoice(invoice);
        JOptionPane.showMessageDialog(this,
            "Invoice marked as funded",
            "Success", JOptionPane.INFORMATION_MESSAGE);
        loadAllInvoices();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
            "Error: " + e.getMessage(),
            "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_markAsFundedBtnActionPerformed

    private void markAsRepaidBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markAsRepaidBtnActionPerformed
        try {
        int selectedRow = invoicesTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this,
                "Please select an invoice",
                "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String currentStatus = invoicesTable.getValueAt(
            selectedRow, 6).toString();

        // Business rule — only FUNDED invoices can be repaid
        if (!currentStatus.equals("FUNDED")) {
            JOptionPane.showMessageDialog(this,
                "Only FUNDED invoices can be marked as repaid",
                "Business Rule Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int invoiceId = (int) invoicesTable.getValueAt(selectedRow, 0);
        Invoice invoice = new Invoice();
        invoice.setInvoiceId(invoiceId);
        invoice.setStatus("REPAID");

        invoiceService.updateInvoice(invoice);
        JOptionPane.showMessageDialog(this,
            "Invoice marked as repaid",
            "Success", JOptionPane.INFORMATION_MESSAGE);
        loadAllInvoices();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
            "Error: " + e.getMessage(),
            "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_markAsRepaidBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        try {
        int selectedRow = invoicesTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this,
                "Please select an invoice to delete",
                "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
            "Are you sure you want to delete this invoice?",
            "Confirm Delete", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) return;

        int invoiceId = (int) invoicesTable.getValueAt(selectedRow, 0);
        Invoice invoice = new Invoice();
        invoice.setInvoiceId(invoiceId);

        invoiceService.deleteInvoice(invoice);
        JOptionPane.showMessageDialog(this,
            "Invoice deleted successfully",
            "Success", JOptionPane.INFORMATION_MESSAGE);
        loadAllInvoices();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
            "Error: " + e.getMessage(),
            "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void searchInvoiceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchInvoiceBtnActionPerformed
        try {
        if (searchInvoiceTxt.getText().trim().isEmpty()) {
            loadAllInvoices();
            return;
        }

        String searchTerm = searchInvoiceTxt.getText().trim().toLowerCase();
        DefaultTableModel model = (DefaultTableModel) invoicesTable.getModel();
        DefaultTableModel filteredModel = new DefaultTableModel(
            new String[]{"ID", "Invoice #", "SME", "Amount",
                         "Issue Date", "Due Date", "Status"}, 0
        );

        for (int i = 0; i < model.getRowCount(); i++) {
            String invoiceNum = model.getValueAt(i, 1).toString().toLowerCase();
            if (invoiceNum.contains(searchTerm)) {
                filteredModel.addRow(new Object[]{
                    model.getValueAt(i, 0),
                    model.getValueAt(i, 1),
                    model.getValueAt(i, 2),
                    model.getValueAt(i, 3),
                    model.getValueAt(i, 4),
                    model.getValueAt(i, 5),
                    model.getValueAt(i, 6)
                });
            }
        }
        invoicesTable.setModel(filteredModel);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
            "Error: " + e.getMessage(),
            "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_searchInvoiceBtnActionPerformed

    private void statusComboActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            String selected = statusCombo.getSelectedItem().toString();
            if (selected.equals("All Status")) {
                loadAllInvoices();
                return;
            }

            List<Invoice> invoices = invoiceService.getAllInvoices();
            DefaultTableModel model = new DefaultTableModel(
                new String[]{"ID", "Invoice #", "SME", "Amount", "Issue Date", "Due Date", "Status"}, 0
            );
            for (int i = 0; i < invoices.size(); i++) {
                Invoice inv = invoices.get(i);
                if (inv.getStatus().equals(selected)) {
                    model.addRow(new Object[]{
                        inv.getInvoiceId(),
                        inv.getInvoiceNumber(),
                        inv.getSme() != null ? inv.getSme().getBusinessName() : "",
                        inv.getAmount(),
                        inv.getIssueDate(),
                        inv.getDueDate(),
                        inv.getStatus()
                    });
                }
            }
            invoicesTable.setModel(model);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Error: " + e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InvoiceManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InvoiceManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InvoiceManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InvoiceManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InvoiceManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton deleteBtn;
    private javax.swing.JTable invoicesTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton markAsFundedBtn;
    private javax.swing.JButton markAsRepaidBtn;
    private javax.swing.JButton searchInvoiceBtn;
    private javax.swing.JTextField searchInvoiceTxt;
    private javax.swing.JComboBox<String> statusCombo;
    private javax.swing.JButton verifyBtn;
    // End of variables declaration//GEN-END:variables
}
