/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rw.rab.view;

import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import rw.rab.model.Invoice;
import rw.rab.model.Sme;
import rw.rab.service.InvoiceService;
import rw.rab.service.SmeService;

/**
 *
 * @author nsumba
 */
public class MyInvoices extends javax.swing.JFrame {
    private InvoiceService invoiceService;
    private SmeService smeService;
    private rw.rab.model.User loggedInUser;

    public MyInvoices(rw.rab.model.User user) {
        initComponents();
        this.loggedInUser = user;
        setLocationRelativeTo(null);
        connectToServer();
        addPlaceholder(invoiceNoTxt, "username");
        addPlaceholder(amountTxt, "Amount");
        addPlaceholder(searchField, "Search By ID");
        loadMyInvoices();
        invoicesTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int row = invoicesTable.getSelectedRow();
                invoiceNoTxt.setText(invoicesTable.getValueAt(row, 1).toString());
                amountTxt.setText(invoicesTable.getValueAt(row, 2).toString());
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dispose();
            }
        });
    }

    private void connectToServer() {
        try {
            Registry registry = LocateRegistry.getRegistry("127.0.0.1", 3000);
            invoiceService = (InvoiceService) registry.lookup("invoice");
            smeService = (SmeService) registry.lookup("sme");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Cannot connect to server: " + e.getMessage(),
                "Connection Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void loadMyInvoices() {
        try {
            List<Invoice> invoices = invoiceService.getAllInvoices();
            DefaultTableModel model = new DefaultTableModel(
                new String[]{"ID", "Invoice #", "Amount", 
                             "Issue Date", "Due Date", "Status"}, 0
            );
            for (int i = 0; i < invoices.size(); i++) {
                Invoice inv = invoices.get(i);
                if (inv.getSme() != null &&
                    inv.getSme().getUser() != null &&
                    inv.getSme().getUser().getUserId() == loggedInUser.getUserId()) {
                    model.addRow(new Object[]{
                        inv.getInvoiceId(),
                        inv.getInvoiceNumber(),
                        inv.getAmount(),
                        inv.getIssueDate(),
                        inv.getDueDate(),
                        inv.getStatus()
                    });
                }
            }
            invoicesTable.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Error loading invoices: " + e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
        }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        invoiceNoTxt = new javax.swing.JTextField();
        registerBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        readAllBtn = new javax.swing.JToggleButton();
        searchField = new javax.swing.JTextField();
        searchByIdBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        invoicesTable = new javax.swing.JTable();
        issuedDate = new com.toedter.calendar.JDateChooser();
        dueDate = new com.toedter.calendar.JDateChooser();
        amountTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(24, 95, 165));

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel1.setText("My Invoices");

        jButton1.setFont(new java.awt.Font("DejaVu Sans", 0, 15)); // NOI18N
        jButton1.setText("Back to Dashboard");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 426, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 0, 15)); // NOI18N
        jLabel2.setText("Invoice Number");

        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 0, 15)); // NOI18N
        jLabel3.setText("Amount(Rwf)");

        jLabel4.setFont(new java.awt.Font("DejaVu Sans", 0, 15)); // NOI18N
        jLabel4.setText("Issue Date");

        jLabel5.setFont(new java.awt.Font("DejaVu Sans", 0, 15)); // NOI18N
        jLabel5.setText("Due Date");

        invoiceNoTxt.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        invoiceNoTxt.setForeground(new java.awt.Color(100, 100, 100));
        invoiceNoTxt.setText("username");
        invoiceNoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invoiceNoTxtActionPerformed(evt);
            }
        });

        registerBtn.setBackground(new java.awt.Color(29, 95, 165));
        registerBtn.setText("Register");
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });

        updateBtn.setBackground(new java.awt.Color(57, 156, 89));
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(200, 72, 30));
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        readAllBtn.setBackground(new java.awt.Color(164, 182, 49));
        readAllBtn.setText("Read All");
        readAllBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readAllBtnActionPerformed(evt);
            }
        });

        searchField.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        searchField.setForeground(new java.awt.Color(100, 100, 100));
        searchField.setText("Search By ID");
        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });

        searchByIdBtn.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        searchByIdBtn.setText("Search");
        searchByIdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByIdBtnActionPerformed(evt);
            }
        });

        invoicesTable.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        invoicesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Invoice #", "Amount", "Issue Date", "Due Date", "Status"
            }
        ));
        jScrollPane1.setViewportView(invoicesTable);

        amountTxt.setForeground(new java.awt.Color(100, 100, 100));
        amountTxt.setText("Amount");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(invoiceNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(amountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addGap(84, 84, 84))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(issuedDate, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(dueDate, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(registerBtn)
                        .addGap(47, 47, 47)
                        .addComponent(updateBtn)
                        .addGap(46, 46, 46)
                        .addComponent(deleteBtn)
                        .addGap(36, 36, 36)
                        .addComponent(readAllBtn)
                        .addGap(68, 68, 68)
                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchByIdBtn)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(invoiceNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(amountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(issuedDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dueDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerBtn)
                    .addComponent(updateBtn)
                    .addComponent(deleteBtn)
                    .addComponent(readAllBtn)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchByIdBtn))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 123, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void invoiceNoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invoiceNoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_invoiceNoTxtActionPerformed

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldActionPerformed

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        try {
        // Technical rule 1 — empty fields
        if (isPlaceholder(invoiceNoTxt, "username") ||
            isPlaceholder(amountTxt, "Amount") ||
            invoiceNoTxt.getText().trim().isEmpty() ||
            amountTxt.getText().trim().isEmpty() ||
            issuedDate.getDate() == null ||
            dueDate.getDate() == null) {
            JOptionPane.showMessageDialog(this,
                "All fields are required",
                "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Technical rule 2 — amount must be numeric
        double amount;
        try {
            amount = Double.parseDouble(amountTxt.getText().trim());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this,
                "Amount must be a valid number",
                "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Business rule 1 — amount must be positive
        if (amount <= 0) {
            JOptionPane.showMessageDialog(this,
                "Invoice amount must be greater than zero",
                "Business Rule Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Business rule 2 — due date must be after issue date
        java.text.SimpleDateFormat sdf = 
            new java.text.SimpleDateFormat("yyyy-MM-dd");
                // New — JDateChooser direct date reading
        java.util.Date issue = issuedDate.getDate();
        java.util.Date due = dueDate.getDate();

        if (issue == null || due == null) {
            JOptionPane.showMessageDialog(this,
                "Please select both issue date and due date",
                "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        };

        if (due.before(issue)) {
            JOptionPane.showMessageDialog(this,
                "Due date must be after issue date",
                "Business Rule Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Get SME linked to this logged in user
        Sme mySme = getOrCreateSmeProfile();

        if (mySme == null) {
            JOptionPane.showMessageDialog(this,
                "No SME profile found for this account. Please contact admin.",
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Invoice invoice = new Invoice();
        invoice.setInvoiceNumber(invoiceNoTxt.getText().trim());
        invoice.setAmount(amount);
        invoice.setIssueDate(issue);
        invoice.setDueDate(due);
        invoice.setStatus("SUBMITTED");
        invoice.setSme(mySme);

        String result = invoiceService.createInvoice(invoice);
        JOptionPane.showMessageDialog(this,
            result, "Success", JOptionPane.INFORMATION_MESSAGE);
        loadMyInvoices();
        clearFields();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
            "Error: " + e.getMessage(),
            "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_registerBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        try {
        int selectedRow = invoicesTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this,
                "Please select an invoice to update",
                "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Business rule — cannot update if not SUBMITTED
        String status = invoicesTable.getValueAt(
            selectedRow, 5).toString();
        if (!status.equals("SUBMITTED")) {
            JOptionPane.showMessageDialog(this,
                "Only SUBMITTED invoices can be updated",
                "Business Rule Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Technical rule — empty fields
        if (isPlaceholder(invoiceNoTxt, "username") ||
            isPlaceholder(amountTxt, "Amount") ||
            invoiceNoTxt.getText().trim().isEmpty() ||
            amountTxt.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Invoice number and amount are required",
                "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int invoiceId = (int) invoicesTable.getValueAt(selectedRow, 0);
        java.text.SimpleDateFormat sdf = 
            new java.text.SimpleDateFormat("yyyy-MM-dd");

        Invoice invoice = new Invoice();
        invoice.setInvoiceId(invoiceId);
        invoice.setInvoiceNumber(invoiceNoTxt.getText().trim());
        double amount;
        try {
            amount = Double.parseDouble(amountTxt.getText().trim());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this,
                "Amount must be a valid number",
                "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (amount <= 0) {
            JOptionPane.showMessageDialog(this,
                "Invoice amount must be greater than zero",
                "Business Rule Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        invoice.setAmount(amount);
        // New — JDateChooser direct date reading
        java.util.Date issue = issuedDate.getDate();
        java.util.Date due = dueDate.getDate();

        if (issue == null || due == null) {
            JOptionPane.showMessageDialog(this,
                "Please select both issue date and due date",
                "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        };
        if (due.before(issue)) {
            JOptionPane.showMessageDialog(this,
                "Due date must be after issue date",
                "Business Rule Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        invoice.setIssueDate(issue);
        invoice.setDueDate(due);
        invoice.setStatus("SUBMITTED");

        String result = invoiceService.updateInvoice(invoice);
        JOptionPane.showMessageDialog(this,
            result, "Success", JOptionPane.INFORMATION_MESSAGE);
        loadMyInvoices();
        clearFields();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
            "Error: " + e.getMessage(),
            "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        try {
        int selectedRow = invoicesTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this,
                "Please select an invoice to delete",
                "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Business rule — cannot delete funded or repaid invoice
        String status = invoicesTable.getValueAt(
            selectedRow, 5).toString();
        if (status.equals("FUNDED") || status.equals("REPAID")) {
            JOptionPane.showMessageDialog(this,
                "Cannot delete a " + status + " invoice",
                "Business Rule Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
            "Are you sure you want to delete this invoice?",
            "Confirm Delete", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) return;

        int invoiceId = (int) invoicesTable.getValueAt(selectedRow, 0);
        Invoice invoice = new Invoice();
        invoice.setInvoiceId(invoiceId);

        invoiceService.deleteInvoice(invoice);
        JOptionPane.showMessageDialog(this,
            "Invoice deleted successfully",
            "Success", JOptionPane.INFORMATION_MESSAGE);
        loadMyInvoices();
        clearFields();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
            "Error: " + e.getMessage(),
            "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void readAllBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readAllBtnActionPerformed
        loadMyInvoices();
    }//GEN-LAST:event_readAllBtnActionPerformed

    private void searchByIdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByIdBtnActionPerformed
        try {
        if (isPlaceholder(searchField, "Search By ID") || searchField.getText().trim().isEmpty()) {
            loadMyInvoices();
            return;
        }
        String term = searchField.getText().trim().toLowerCase();
        DefaultTableModel model = (DefaultTableModel) invoicesTable.getModel();
        DefaultTableModel filtered = new DefaultTableModel(
            new String[]{"ID", "Invoice #", "Amount",
                         "Issue Date", "Due Date", "Status"}, 0
        );
        for (int i = 0; i < model.getRowCount(); i++) {
            if (model.getValueAt(i, 1).toString()
                    .toLowerCase().contains(term)) {
                filtered.addRow(new Object[]{
                    model.getValueAt(i, 0),
                    model.getValueAt(i, 1),
                    model.getValueAt(i, 2),
                    model.getValueAt(i, 3),
                    model.getValueAt(i, 4),
                    model.getValueAt(i, 5)
                });
            }
        }
        invoicesTable.setModel(filtered);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
            "Error: " + e.getMessage(),
            "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_searchByIdBtnActionPerformed

    private Sme getOrCreateSmeProfile() {
        try {
            Sme sme = smeService.getSmeByUserId(loggedInUser);
            if (sme != null) {
                return sme;
            }

            Sme newSme = new Sme();
            newSme.setBusinessName(loggedInUser.getUsername());
            newSme.setRegistrationNumber("REG-" + loggedInUser.getUserId());
            newSme.setPhone("");
            newSme.setCreditLimit(0);
            newSme.setUser(loggedInUser);
            smeService.createSme(newSme);

            return smeService.getSmeByUserId(loggedInUser);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Error preparing SME profile: " + e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
            return null;
        }
    }

    private void addPlaceholder(final javax.swing.JTextField field, final String placeholder) {
        field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (field.getText().equals(placeholder)) {
                    field.setText("");
                    field.setForeground(new java.awt.Color(0, 0, 0));
                }
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                if (field.getText().trim().isEmpty()) {
                    field.setText(placeholder);
                    field.setForeground(new java.awt.Color(100, 100, 100));
                }
            }
        });
    }

    private boolean isPlaceholder(javax.swing.JTextField field, String placeholder) {
        return field.getText().trim().equals(placeholder);
    }

    private void clearFields() {
    invoiceNoTxt.setText("username");
    invoiceNoTxt.setForeground(new java.awt.Color(100, 100, 100));
    amountTxt.setText("Amount");
    amountTxt.setForeground(new java.awt.Color(100, 100, 100));
    issuedDate.setDate(null);
    dueDate.setDate(null);
    searchField.setText("Search By ID");
    searchField.setForeground(new java.awt.Color(100, 100, 100));
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyInvoices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyInvoices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyInvoices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyInvoices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyInvoices(new rw.rab.model.User()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountTxt;
    private javax.swing.JButton deleteBtn;
    private com.toedter.calendar.JDateChooser dueDate;
    private javax.swing.JTextField invoiceNoTxt;
    private javax.swing.JTable invoicesTable;
    private com.toedter.calendar.JDateChooser issuedDate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton readAllBtn;
    private javax.swing.JButton registerBtn;
    private javax.swing.JButton searchByIdBtn;
    private javax.swing.JTextField searchField;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
