/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rw.rab.view;

/**
 *
 * @author nsumba
 */
public class ReportsPage extends javax.swing.JFrame {

    private rw.rab.model.User loggedInUser;
    private rw.rab.service.InvoiceService invoiceService;
    private rw.rab.service.FundingService fundingService;
    private rw.rab.service.UserService userService;

    public ReportsPage(rw.rab.model.User user) {
        initComponents();
        this.loggedInUser = user;
        setLocationRelativeTo(null);
        connectToServer();
        loadInvoicePreview();
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dispose();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        invoiceReport = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        usersExportPdfBtn = new javax.swing.JButton();
        invoiceExportCsvBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        invoiceExportPdfBtn = new javax.swing.JButton();
        fundingExportCsvBtn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        fundingExportPdfBtn = new javax.swing.JButton();
        usersExportCsvBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(24, 95, 165));

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel1.setText("My Invoices");

        jButton1.setFont(new java.awt.Font("DejaVu Sans", 0, 15)); // NOI18N
        jButton1.setText("Back to Dashboard");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        invoiceReport.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        invoiceReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Invoice#", "SME", "Amount", "Issue Date", "Status"
            }
        ));
        jScrollPane1.setViewportView(invoiceReport);

        jLabel6.setText("Preview-Invoice Report");

        jLabel7.setText("Invoice Report");

        jLabel8.setFont(new java.awt.Font("Ubuntu Sans", 0, 10)); // NOI18N
        jLabel8.setText("All Invoices with Status");

        usersExportPdfBtn.setBackground(new java.awt.Color(24, 95, 165));
        usersExportPdfBtn.setText("Export PDF");
        usersExportPdfBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usersExportPdfBtnActionPerformed(evt);
            }
        });

        invoiceExportCsvBtn.setBackground(new java.awt.Color(57, 156, 89));
        invoiceExportCsvBtn.setText("Export CSV");
        invoiceExportCsvBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invoiceExportCsvBtnActionPerformed(evt);
            }
        });

        jLabel9.setText("Funding Report");

        jLabel10.setFont(new java.awt.Font("Ubuntu Sans", 0, 10)); // NOI18N
        jLabel10.setText("All Funding Transactions");

        invoiceExportPdfBtn.setBackground(new java.awt.Color(24, 95, 165));
        invoiceExportPdfBtn.setText("Export PDF");
        invoiceExportPdfBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invoiceExportPdfBtnActionPerformed(evt);
            }
        });

        fundingExportCsvBtn.setBackground(new java.awt.Color(57, 156, 89));
        fundingExportCsvBtn.setText("Export CSV");
        fundingExportCsvBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fundingExportCsvBtnActionPerformed(evt);
            }
        });

        jLabel11.setText("Users Report");

        jLabel12.setFont(new java.awt.Font("Ubuntu Sans", 0, 10)); // NOI18N
        jLabel12.setText("All Users Report");

        fundingExportPdfBtn.setBackground(new java.awt.Color(24, 95, 165));
        fundingExportPdfBtn.setText("Export PDF");
        fundingExportPdfBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fundingExportPdfBtnActionPerformed(evt);
            }
        });

        usersExportCsvBtn.setBackground(new java.awt.Color(57, 156, 89));
        usersExportCsvBtn.setText("Export CSV");
        usersExportCsvBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usersExportCsvBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(invoiceExportPdfBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(invoiceExportCsvBtn)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(130, 130, 130)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel12)))
                .addGap(61, 61, 61))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(fundingExportPdfBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fundingExportCsvBtn)
                .addGap(51, 51, 51)
                .addComponent(usersExportPdfBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usersExportCsvBtn)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usersExportPdfBtn)
                    .addComponent(invoiceExportCsvBtn)
                    .addComponent(invoiceExportPdfBtn)
                    .addComponent(fundingExportCsvBtn)
                    .addComponent(fundingExportPdfBtn)
                    .addComponent(usersExportCsvBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void invoiceExportCsvBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invoiceExportCsvBtnActionPerformed
        exportInvoicesToCsv();
    }//GEN-LAST:event_invoiceExportCsvBtnActionPerformed

    private void usersExportPdfBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usersExportPdfBtnActionPerformed
        exportUsersToPdf();
    }//GEN-LAST:event_usersExportPdfBtnActionPerformed

    private void invoiceExportPdfBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invoiceExportPdfBtnActionPerformed
        exportInvoicesToPdf();
    }//GEN-LAST:event_invoiceExportPdfBtnActionPerformed

    private void fundingExportCsvBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fundingExportCsvBtnActionPerformed
        exportFundingsToCsv();
    }//GEN-LAST:event_fundingExportCsvBtnActionPerformed

    private void fundingExportPdfBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fundingExportPdfBtnActionPerformed
        exportFundingsToPdf();
    }//GEN-LAST:event_fundingExportPdfBtnActionPerformed

    private void usersExportCsvBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usersExportCsvBtnActionPerformed
        exportUsersToCsv();
    }//GEN-LAST:event_usersExportCsvBtnActionPerformed

    private void connectToServer() {
        try {
            java.rmi.registry.Registry registry = java.rmi.registry.LocateRegistry.getRegistry("127.0.0.1", 3000);
            invoiceService = (rw.rab.service.InvoiceService) registry.lookup("invoice");
            fundingService = (rw.rab.service.FundingService) registry.lookup("funding");
            userService = (rw.rab.service.UserService) registry.lookup("user");
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Cannot connect to server: " + e.getMessage(),
                "Connection Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    private void loadInvoicePreview() {
        try {
            java.util.List<rw.rab.model.Invoice> invoices = invoiceService.getAllInvoices();
            javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(
                new String[]{"Invoice #", "SME", "Amount", "Issue Date", "Status"}, 0
            );
            for (int i = 0; i < invoices.size(); i++) {
                rw.rab.model.Invoice inv = invoices.get(i);
                model.addRow(new Object[]{
                    inv.getInvoiceNumber(),
                    inv.getSme() != null ? inv.getSme().getBusinessName() : "",
                    inv.getAmount(),
                    inv.getIssueDate(),
                    inv.getStatus()
                });
            }
            invoiceReport.setModel(model);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Error loading preview: " + e.getMessage(),
                "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    private void exportInvoicesToPdf() {
        try {
            javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
            fileChooser.setSelectedFile(new java.io.File("InvoiceReport.pdf"));
            int result = fileChooser.showSaveDialog(this);
            if (result != javax.swing.JFileChooser.APPROVE_OPTION) return;

            String path = fileChooser.getSelectedFile().getAbsolutePath();
            if (!path.endsWith(".pdf")) path += ".pdf";

            com.itextpdf.text.Document document = new com.itextpdf.text.Document();
            com.itextpdf.text.pdf.PdfWriter.getInstance(
                document, new java.io.FileOutputStream(path));
            document.open();

            com.itextpdf.text.Font titleFont = new com.itextpdf.text.Font(
                com.itextpdf.text.Font.FontFamily.HELVETICA, 16,
                com.itextpdf.text.Font.BOLD);
            document.add(new com.itextpdf.text.Paragraph(
                "SME Trade Credit Financing System", titleFont));
            document.add(new com.itextpdf.text.Paragraph("Invoice Report"));
            document.add(new com.itextpdf.text.Paragraph(
                "Generated: " + new java.util.Date().toString()));
            document.add(com.itextpdf.text.Chunk.NEWLINE);

            com.itextpdf.text.pdf.PdfPTable table = new com.itextpdf.text.pdf.PdfPTable(5);
            table.setWidthPercentage(100);
            table.addCell("Invoice #");
            table.addCell("SME");
            table.addCell("Amount");
            table.addCell("Issue Date");
            table.addCell("Status");

            java.util.List<rw.rab.model.Invoice> invoices = invoiceService.getAllInvoices();
            for (int i = 0; i < invoices.size(); i++) {
                rw.rab.model.Invoice inv = invoices.get(i);
                table.addCell(inv.getInvoiceNumber() != null ? inv.getInvoiceNumber() : "");
                table.addCell(inv.getSme() != null ? inv.getSme().getBusinessName() : "");
                table.addCell(String.valueOf(inv.getAmount()));
                table.addCell(inv.getIssueDate() != null ? inv.getIssueDate().toString() : "");
                table.addCell(inv.getStatus() != null ? inv.getStatus() : "");
            }

            document.add(table);
            document.close();

            javax.swing.JOptionPane.showMessageDialog(this,
                "Invoice PDF exported successfully to:\n" + path,
                "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Error exporting PDF: " + e.getMessage(),
                "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    private void exportInvoicesToCsv() {
        try {
            javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
            fileChooser.setSelectedFile(new java.io.File("InvoiceReport.csv"));
            int result = fileChooser.showSaveDialog(this);
            if (result != javax.swing.JFileChooser.APPROVE_OPTION) return;

            String path = fileChooser.getSelectedFile().getAbsolutePath();
            if (!path.endsWith(".csv")) path += ".csv";

            java.util.List<rw.rab.model.Invoice> invoices = invoiceService.getAllInvoices();
            java.io.FileWriter fw = new java.io.FileWriter(path);
            fw.write("Invoice#,SME,Amount,Issue Date,Due Date,Status\n");

            for (int i = 0; i < invoices.size(); i++) {
                rw.rab.model.Invoice inv = invoices.get(i);
                fw.write(
                    (inv.getInvoiceNumber() != null ? inv.getInvoiceNumber() : "") + "," +
                    (inv.getSme() != null ? inv.getSme().getBusinessName() : "") + "," +
                    inv.getAmount() + "," +
                    (inv.getIssueDate() != null ? inv.getIssueDate().toString() : "") + "," +
                    (inv.getDueDate() != null ? inv.getDueDate().toString() : "") + "," +
                    (inv.getStatus() != null ? inv.getStatus() : "") + "\n"
                );
            }
            fw.close();

            javax.swing.JOptionPane.showMessageDialog(this,
                "Invoice CSV exported successfully to:\n" + path,
                "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Error exporting CSV: " + e.getMessage(),
                "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    private void exportFundingsToPdf() {
        try {
            javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
            fileChooser.setSelectedFile(new java.io.File("FundingReport.pdf"));
            int result = fileChooser.showSaveDialog(this);
            if (result != javax.swing.JFileChooser.APPROVE_OPTION) return;

            String path = fileChooser.getSelectedFile().getAbsolutePath();
            if (!path.endsWith(".pdf")) path += ".pdf";

            com.itextpdf.text.Document document = new com.itextpdf.text.Document();
            com.itextpdf.text.pdf.PdfWriter.getInstance(
                document, new java.io.FileOutputStream(path));
            document.open();

            com.itextpdf.text.Font titleFont = new com.itextpdf.text.Font(
                com.itextpdf.text.Font.FontFamily.HELVETICA, 16,
                com.itextpdf.text.Font.BOLD);
            document.add(new com.itextpdf.text.Paragraph(
                "SME Trade Credit Financing System", titleFont));
            document.add(new com.itextpdf.text.Paragraph("Funding Report"));
            document.add(new com.itextpdf.text.Paragraph(
                "Generated: " + new java.util.Date().toString()));
            document.add(com.itextpdf.text.Chunk.NEWLINE);

            com.itextpdf.text.pdf.PdfPTable table = new com.itextpdf.text.pdf.PdfPTable(4);
            table.setWidthPercentage(100);
            table.addCell("Funding ID");
            table.addCell("Invoice #");
            table.addCell("Amount Funded");
            table.addCell("Date");

            java.util.List<rw.rab.model.Funding> fundings = fundingService.getAllFundings();
            for (int i = 0; i < fundings.size(); i++) {
                rw.rab.model.Funding f = fundings.get(i);
                table.addCell(String.valueOf(f.getFundingId()));
                table.addCell(f.getInvoice() != null ? f.getInvoice().getInvoiceNumber() : "");
                table.addCell(String.valueOf(f.getFundedAmount()));
                table.addCell(f.getFundedDate() != null ? f.getFundedDate().toString() : "");
            }

            document.add(table);
            document.close();

            javax.swing.JOptionPane.showMessageDialog(this,
                "Funding PDF exported successfully to:\n" + path,
                "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Error exporting PDF: " + e.getMessage(),
                "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    private void exportFundingsToCsv() {
        try {
            javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
            fileChooser.setSelectedFile(new java.io.File("FundingReport.csv"));
            int result = fileChooser.showSaveDialog(this);
            if (result != javax.swing.JFileChooser.APPROVE_OPTION) return;

            String path = fileChooser.getSelectedFile().getAbsolutePath();
            if (!path.endsWith(".csv")) path += ".csv";

            java.util.List<rw.rab.model.Funding> fundings = fundingService.getAllFundings();
            java.io.FileWriter fw = new java.io.FileWriter(path);
            fw.write("Funding ID,Invoice #,Amount Funded,Date\n");

            for (int i = 0; i < fundings.size(); i++) {
                rw.rab.model.Funding f = fundings.get(i);
                fw.write(
                    f.getFundingId() + "," +
                    (f.getInvoice() != null ? f.getInvoice().getInvoiceNumber() : "") + "," +
                    f.getFundedAmount() + "," +
                    (f.getFundedDate() != null ? f.getFundedDate().toString() : "") + "\n"
                );
            }
            fw.close();

            javax.swing.JOptionPane.showMessageDialog(this,
                "Funding CSV exported successfully to:\n" + path,
                "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Error exporting CSV: " + e.getMessage(),
                "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    private void exportUsersToPdf() {
        try {
            javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
            fileChooser.setSelectedFile(new java.io.File("UsersReport.pdf"));
            int result = fileChooser.showSaveDialog(this);
            if (result != javax.swing.JFileChooser.APPROVE_OPTION) return;

            String path = fileChooser.getSelectedFile().getAbsolutePath();
            if (!path.endsWith(".pdf")) path += ".pdf";

            com.itextpdf.text.Document document = new com.itextpdf.text.Document();
            com.itextpdf.text.pdf.PdfWriter.getInstance(
                document, new java.io.FileOutputStream(path));
            document.open();

            com.itextpdf.text.Font titleFont = new com.itextpdf.text.Font(
                com.itextpdf.text.Font.FontFamily.HELVETICA, 16,
                com.itextpdf.text.Font.BOLD);
            document.add(new com.itextpdf.text.Paragraph(
                "SME Trade Credit Financing System", titleFont));
            document.add(new com.itextpdf.text.Paragraph("Users Report"));
            document.add(new com.itextpdf.text.Paragraph(
                "Generated: " + new java.util.Date().toString()));
            document.add(com.itextpdf.text.Chunk.NEWLINE);

            com.itextpdf.text.pdf.PdfPTable table = new com.itextpdf.text.pdf.PdfPTable(4);
            table.setWidthPercentage(100);
            table.addCell("ID");
            table.addCell("Username");
            table.addCell("Email");
            table.addCell("Role");

            java.util.List<rw.rab.model.User> users = userService.getAllUsers();
            for (int i = 0; i < users.size(); i++) {
                rw.rab.model.User u = users.get(i);
                table.addCell(String.valueOf(u.getUserId()));
                table.addCell(u.getUsername() != null ? u.getUsername() : "");
                table.addCell(u.getEmail() != null ? u.getEmail() : "");
                table.addCell(u.getRole() != null ? u.getRole() : "");
            }

            document.add(table);
            document.close();

            javax.swing.JOptionPane.showMessageDialog(this,
                "Users PDF exported successfully to:\n" + path,
                "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Error exporting PDF: " + e.getMessage(),
                "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    private void exportUsersToCsv() {
        try {
            javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
            fileChooser.setSelectedFile(new java.io.File("UsersReport.csv"));
            int result = fileChooser.showSaveDialog(this);
            if (result != javax.swing.JFileChooser.APPROVE_OPTION) return;

            String path = fileChooser.getSelectedFile().getAbsolutePath();
            if (!path.endsWith(".csv")) path += ".csv";

            java.util.List<rw.rab.model.User> users = userService.getAllUsers();
            java.io.FileWriter fw = new java.io.FileWriter(path);
            fw.write("ID,Username,Email,Role\n");

            for (int i = 0; i < users.size(); i++) {
                rw.rab.model.User u = users.get(i);
                fw.write(
                    u.getUserId() + "," +
                    (u.getUsername() != null ? u.getUsername() : "") + "," +
                    (u.getEmail() != null ? u.getEmail() : "") + "," +
                    (u.getRole() != null ? u.getRole() : "") + "\n"
                );
            }
            fw.close();

            javax.swing.JOptionPane.showMessageDialog(this,
                "Users CSV exported successfully to:\n" + path,
                "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Error exporting CSV: " + e.getMessage(),
                "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportsPage(new rw.rab.model.User()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fundingExportCsvBtn;
    private javax.swing.JButton fundingExportPdfBtn;
    private javax.swing.JButton invoiceExportCsvBtn;
    private javax.swing.JButton invoiceExportPdfBtn;
    private javax.swing.JTable invoiceReport;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton usersExportCsvBtn;
    private javax.swing.JButton usersExportPdfBtn;
    // End of variables declaration//GEN-END:variables
}
