/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rw.rab.view;

import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import rw.rab.model.Investor;
import rw.rab.model.Sme;
import rw.rab.model.User;
import rw.rab.service.InvestorService;
import rw.rab.service.SmeService;
import rw.rab.service.UserService;

/**
 *
 * @author nsumba
 */
public class UserManagement extends javax.swing.JFrame {
    private UserService userService;
    private SmeService smeService;
    private InvestorService investorService;
    /**
     * Creates new form UserManagement
     */
    public UserManagement() {
        initComponents();
        setLocationRelativeTo(null);
        connectToServer();
        addPlaceholder(usernameManageUser, "username");
        addPlaceholder(emailManageUser, "Email");
        addPasswordPlaceholder(passwordManageUser, "jPasswordField1");
        addPlaceholder(searchUser, "Search By ID");
        loadAllUsers();
        usersTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int row = usersTable.getSelectedRow();
                usernameManageUser.setText(usersTable.getValueAt(row, 1).toString());
                emailManageUser.setText(usersTable.getValueAt(row, 2).toString());
                roleManageUserCombo.setSelectedItem(usersTable.getValueAt(row, 3).toString());
            }
        });
        backToDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dispose();
            }
        });
    }
    
    private void connectToServer(){
        try{
            Registry  registry = LocateRegistry.getRegistry("127.0.0.1", 3000);
            userService = (UserService) registry.lookup("user");
            smeService = (SmeService) registry.lookup("sme");
            investorService = (InvestorService) registry.lookup("investor");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Cannot connect to server: " + e.getMessage(), "Connection Error", JOptionPane.ERROR_MESSAGE);
            
        }
    }
    
    private void loadAllUsers(){
        try{
            List<User> users = userService.getAllUsers();
            DefaultTableModel model = new DefaultTableModel(
            new String[]{"ID", "Username", "Email", "Role"},0
            );
            
            for (int i = 0; i < users.size(); i++) {
                User u = users.get(i);
                model.addRow(new Object[]{
                    u.getUserId(),
                    u.getUsername(),
                    u.getEmail(),
                    u.getRole()
                });
            }
            usersTable.setModel(model);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,
                    "Error loading users"+ e.getMessage(), 
                    "Error", JOptionPane.ERROR_MESSAGE);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        backToDashboard = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        usernameManageUser = new javax.swing.JTextField();
        emailManageUser = new javax.swing.JTextField();
        roleManageUserCombo = new javax.swing.JComboBox<>();
        passwordManageUser = new javax.swing.JPasswordField();
        registerUserBtn = new javax.swing.JButton();
        updateUserBtn = new javax.swing.JButton();
        deleteUserBtn = new javax.swing.JButton();
        readAllUserBtn = new javax.swing.JToggleButton();
        searchUser = new javax.swing.JTextField();
        searchByIdBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        usersTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(24, 95, 165));

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel1.setText("Manage Users");

        backToDashboard.setFont(new java.awt.Font("DejaVu Sans", 0, 15)); // NOI18N
        backToDashboard.setText("Back to Dashboard");
        backToDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToDashboardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backToDashboard)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(backToDashboard))
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 0, 15)); // NOI18N
        jLabel2.setText("Username");

        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 0, 15)); // NOI18N
        jLabel3.setText("Password");

        jLabel4.setFont(new java.awt.Font("DejaVu Sans", 0, 15)); // NOI18N
        jLabel4.setText("Email");

        jLabel5.setFont(new java.awt.Font("DejaVu Sans", 0, 15)); // NOI18N
        jLabel5.setText("Role");

        usernameManageUser.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        usernameManageUser.setForeground(new java.awt.Color(100, 100, 100));
        usernameManageUser.setText("username");
        usernameManageUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameManageUserActionPerformed(evt);
            }
        });

        emailManageUser.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        emailManageUser.setForeground(new java.awt.Color(100, 100, 100));
        emailManageUser.setText("Email");

        roleManageUserCombo.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        roleManageUserCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SME", "Investor" }));
        roleManageUserCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleManageUserComboActionPerformed(evt);
            }
        });

        passwordManageUser.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        passwordManageUser.setText("jPasswordField1");

        registerUserBtn.setBackground(new java.awt.Color(29, 95, 165));
        registerUserBtn.setText("Register");
        registerUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerUserBtnActionPerformed(evt);
            }
        });

        updateUserBtn.setBackground(new java.awt.Color(57, 156, 89));
        updateUserBtn.setText("Update");
        updateUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateUserBtnActionPerformed(evt);
            }
        });

        deleteUserBtn.setBackground(new java.awt.Color(200, 72, 30));
        deleteUserBtn.setText("Delete");
        deleteUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteUserBtnActionPerformed(evt);
            }
        });

        readAllUserBtn.setBackground(new java.awt.Color(64, 182, 49));
        readAllUserBtn.setText("Read All");
        readAllUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readAllUserBtnActionPerformed(evt);
            }
        });

        searchUser.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        searchUser.setForeground(new java.awt.Color(100, 100, 100));
        searchUser.setText("Search By ID");
        searchUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchUserActionPerformed(evt);
            }
        });

        searchByIdBtn.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        searchByIdBtn.setText("Search");
        searchByIdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByIdBtnActionPerformed(evt);
            }
        });

        usersTable.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        usersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Username", "Email", "Role"
            }
        ));
        jScrollPane1.setViewportView(usersTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(usernameManageUser, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(passwordManageUser, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(emailManageUser, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(84, 84, 84))
                            .addComponent(roleManageUserCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(registerUserBtn)
                        .addGap(47, 47, 47)
                        .addComponent(updateUserBtn)
                        .addGap(46, 46, 46)
                        .addComponent(deleteUserBtn)
                        .addGap(36, 36, 36)
                        .addComponent(readAllUserBtn)
                        .addGap(68, 68, 68)
                        .addComponent(searchUser, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchByIdBtn)
                        .addGap(0, 12, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameManageUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailManageUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roleManageUserCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordManageUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerUserBtn)
                    .addComponent(updateUserBtn)
                    .addComponent(deleteUserBtn)
                    .addComponent(readAllUserBtn)
                    .addComponent(searchUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchByIdBtn))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 123, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameManageUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameManageUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameManageUserActionPerformed

    private void roleManageUserComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleManageUserComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roleManageUserComboActionPerformed

    private void searchUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchUserActionPerformed

    private void registerUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerUserBtnActionPerformed
        try{
            //Technical rule 1 - empty field check
            if(isPlaceholder(usernameManageUser, "username") ||
                isPlaceholder(emailManageUser, "Email") ||
                new String(passwordManageUser.getPassword()).trim().equals("jPasswordField1") ||
                usernameManageUser.getText().trim().isEmpty() || 
                emailManageUser.getText().trim().isEmpty() ||
                new String(passwordManageUser.getPassword()).trim().isEmpty()){
                JOptionPane.showMessageDialog(this,"Username, password and email are required",
                        "Validation Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            //  Technical rule 2 - email format check
            if(!isValidEmail(emailManageUser.getText().trim())){
                JOptionPane.showMessageDialog(this,
                        "Please enter a valid real email address",
                        "Validation Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Technical rule 3 - password length
            if(new String(passwordManageUser.getPassword()).length() < 6){
               JOptionPane.showMessageDialog(this,
                       "Password must be at least 6 characters",
                       "Validation Error", JOptionPane.ERROR_MESSAGE);
               return;
            };
            User user = new User();
            user.setUsername(usernameManageUser.getText().trim());
            user.setPassword(new String(passwordManageUser.getPassword()).trim());
            user.setEmail(emailManageUser.getText().trim());
            user.setRole(roleManageUserCombo.getSelectedItem().toString());

            String result = userService.createUser(user);
            User createdUser = findCreatedUser(user);
            createProfileForRole(createdUser);
            JOptionPane.showMessageDialog(this,
                result, "Success", JOptionPane.INFORMATION_MESSAGE);
            loadAllUsers();
            clearFields();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,
                    "Error registering User"+ e.getMessage(), 
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_registerUserBtnActionPerformed

    private void updateUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateUserBtnActionPerformed
        try {
        // Must select a row first
        int selectedRow = usersTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this,
                "Please select a user from the table to update",
                "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Technical rule 1 — empty check
        if (isPlaceholder(usernameManageUser, "username") ||
            isPlaceholder(emailManageUser, "Email") ||
            usernameManageUser.getText().trim().isEmpty() ||
            emailManageUser.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Username and email cannot be empty",
                "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!isValidEmail(emailManageUser.getText().trim())) {
            JOptionPane.showMessageDialog(this,
                "Please enter a valid real email address",
                "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int userId = (int) usersTable.getValueAt(selectedRow, 0);
        User user = new User();
        user.setUserId(userId);
        user.setUsername(usernameManageUser.getText().trim());
        String password = new String(passwordManageUser.getPassword()).trim();
        if (password.equals("jPasswordField1") || password.isEmpty()) {
            User existing = new User();
            existing.setUserId(userId);
            existing = userService.getUserById(existing);
            if (existing != null) {
                password = existing.getPassword();
            }
        }
        user.setPassword(password);
        user.setEmail(emailManageUser.getText().trim());
        user.setRole(roleManageUserCombo.getSelectedItem().toString());

        String result = userService.updateUser(user);
        createProfileForRole(user);
        JOptionPane.showMessageDialog(this,
            result, "Success", JOptionPane.INFORMATION_MESSAGE);
        loadAllUsers();
        clearFields();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
            "Error: " + e.getMessage(),
            "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_updateUserBtnActionPerformed

    private void deleteUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteUserBtnActionPerformed
        try {
        int selectedRow = usersTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this,
                "Please select a user from the table to delete",
                "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Business rule — confirm before delete
        int confirm = JOptionPane.showConfirmDialog(this,
            "Are you sure you want to delete this user?",
            "Confirm Delete", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) return;

        int userId = (int) usersTable.getValueAt(selectedRow, 0);
        User user = new User();
        user.setUserId(userId);

        String result = userService.deleteUser(user);
        JOptionPane.showMessageDialog(this,
            result, "Success", JOptionPane.INFORMATION_MESSAGE);
        loadAllUsers();
        clearFields();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
            "Error: " + e.getMessage(),
            "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_deleteUserBtnActionPerformed

    private void readAllUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readAllUserBtnActionPerformed
        loadAllUsers();
    }//GEN-LAST:event_readAllUserBtnActionPerformed

    private void searchByIdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByIdBtnActionPerformed
        try {
        // Technical rule — search field not empty
        if (isPlaceholder(searchUser, "Search By ID") || searchUser.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Please enter an ID to search",
                "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Technical rule — must be a number
        int id;
        try {
            id = Integer.parseInt(searchUser.getText().trim());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this,
                "ID must be a number",
                "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        User user = new User();
        user.setUserId(id);
        User found = userService.getUserById(user);

        if (found != null) {
            DefaultTableModel model = new DefaultTableModel(
                new String[]{"ID", "Username", "Email", "Role"}, 0
            );
            model.addRow(new Object[]{
                found.getUserId(),
                found.getUsername(),
                found.getEmail(),
                found.getRole()
            });
            usersTable.setModel(model);
        } else {
            JOptionPane.showMessageDialog(this,
                "No user found with ID: " + id,
                "Not Found", JOptionPane.WARNING_MESSAGE);
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
            "Error: " + e.getMessage(),
            "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_searchByIdBtnActionPerformed

    private void backToDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToDashboardActionPerformed
        this.dispose();
    }//GEN-LAST:event_backToDashboardActionPerformed
    private User findCreatedUser(User user) {
        try {
            List<User> users = userService.getAllUsers();
            for (int i = 0; i < users.size(); i++) {
                User existing = users.get(i);
                if (existing.getUsername() != null && existing.getEmail() != null &&
                    existing.getUsername().equals(user.getUsername()) &&
                    existing.getEmail().equals(user.getEmail())) {
                    return existing;
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "User saved, but profile lookup failed: " + e.getMessage(),
                "Warning", JOptionPane.WARNING_MESSAGE);
        }
        return null;
    }

    private void createProfileForRole(User user) {
        if (user == null || user.getRole() == null) {
            return;
        }

        try {
            String role = user.getRole().trim();
            if (role.equalsIgnoreCase("SME")) {
                Sme existing = smeService.getSmeByUserId(user);
                if (existing == null) {
                    Sme sme = new Sme();
                    sme.setBusinessName(user.getUsername());
                    sme.setRegistrationNumber("REG-" + user.getUserId());
                    sme.setPhone("");
                    sme.setCreditLimit(0);
                    sme.setUser(user);
                    smeService.createSme(sme);
                }
            } else if (role.equalsIgnoreCase("INVESTOR")) {
                Investor existing = investorService.getInvestorByUserId(user);
                if (existing == null) {
                    Investor investor = new Investor();
                    investor.setFullName(user.getUsername());
                    investor.setPhone("");
                    investor.setAvailableBalance(0);
                    investor.setUser(user);
                    investorService.createInvestor(investor);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "User saved, but profile creation failed: " + e.getMessage(),
                "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void addPlaceholder(final javax.swing.JTextField field, final String placeholder) {
        field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (field.getText().equals(placeholder)) {
                    field.setText("");
                    field.setForeground(new java.awt.Color(0, 0, 0));
                }
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                if (field.getText().trim().isEmpty()) {
                    field.setText(placeholder);
                    field.setForeground(new java.awt.Color(100, 100, 100));
                }
            }
        });
    }

    private void addPasswordPlaceholder(final javax.swing.JPasswordField field, final String placeholder) {
        field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (new String(field.getPassword()).equals(placeholder)) {
                    field.setText("");
                    field.setForeground(new java.awt.Color(0, 0, 0));
                }
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                if (new String(field.getPassword()).trim().isEmpty()) {
                    field.setText(placeholder);
                    field.setForeground(new java.awt.Color(100, 100, 100));
                }
            }
        });
    }

    private boolean isPlaceholder(javax.swing.JTextField field, String placeholder) {
        return field.getText().trim().equals(placeholder);
    }

    private boolean isValidEmail(String email) {
        if (email == null) {
            return false;
        }
        return email.matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$");
    }

    private void clearFields() {
    usernameManageUser.setText("username");
    usernameManageUser.setForeground(new java.awt.Color(100, 100, 100));
    passwordManageUser.setText("jPasswordField1");
    passwordManageUser.setForeground(new java.awt.Color(100, 100, 100));
    emailManageUser.setText("Email");
    emailManageUser.setForeground(new java.awt.Color(100, 100, 100));
    roleManageUserCombo.setSelectedIndex(0);
    searchUser.setText("Search By ID");
    searchUser.setForeground(new java.awt.Color(100, 100, 100));
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backToDashboard;
    private javax.swing.JButton deleteUserBtn;
    private javax.swing.JTextField emailManageUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPasswordField passwordManageUser;
    private javax.swing.JToggleButton readAllUserBtn;
    private javax.swing.JButton registerUserBtn;
    private javax.swing.JComboBox<String> roleManageUserCombo;
    private javax.swing.JButton searchByIdBtn;
    private javax.swing.JTextField searchUser;
    private javax.swing.JButton updateUserBtn;
    private javax.swing.JTextField usernameManageUser;
    private javax.swing.JTable usersTable;
    // End of variables declaration//GEN-END:variables
}
